eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
    enabled: true

#logging:
 # pattern:
  #  console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId},%X{spanId}] %-5level %logger - %msg%n"

springdoc:
  api-docs:
    enabled: true

  group-configs:
    - group: products
      paths-to-match: /api/products/**

    - group: categories
      paths-to-match: /api/categories/**

  swagger-ui:
    path: /swagger-ui.html
  override-with-generic-response: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

file:
  upload-dir: ${PRODUCT_IMAGE_DIR:/app/uploads}