springdoc:
  api-docs:
    enabled: true

  group-configs:
    - group: products
      paths-to-match: /api/products/**

    - group: categories
      paths-to-match: /api/categories/**
  swagger-ui:
    path: /swagger-ui.html
  override-with-generic-response: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json